### PR TITLE
Update to v0.8.0

### PR DESCRIPTION
**Pull request by raptorsun**
Align the master branch to upstream tag v0.8.0

### CODE REVIEW

**Comment by simonpasquier** [comment]
/hold

we would need a downstream version of prometheus/procfs only if openshift/node_exporter depended on it but it isn't the case apparently

https://github.com/openshift/node_exporter/blob/af2f49cac92d4ec56fd495c0ecfc0e0a4149eea5/go.mod#L25

**Comment by raptorsun** [comment]
> /hold
> 
> we would need a downstream version of prometheus/procfs only if openshift/node_exporter depended on it but it isn't the case apparently
> 
> https://github.com/openshift/node_exporter/blob/af2f49cac92d4ec56fd495c0ecfc0e0a4149eea5/go.mod#L25

ok, we leave this aside. Node Exporter uses github.com/prometheus/procfs directly.

**Comment by jan--f** [comment]
it also looks like we never used it? Should we get rid of this fork then?

**Comment by simonpasquier** [comment]
We used it a while ago (> 2 years probably) because we had to carry a downstream patch and didn't want to have a go.mod replace directive in github.com/openshift/node_exporter pointing to github.com/(individual_contributor)/procfs.
Now that we "own" github.com/rhobs, we could use it for dependencies that need to carry downstream patches and archive this fork (another example would be github.com/prometheus/common). Since dependencies are always vendored, the final bits are what lives under vendor/ in github.com/openshift/node_exporter/ anyway.

**Comment by simonpasquier** [comment]
I'm experimenting with another option which is to carry the dependency patch directly in the downstream repository that needs it:
https://github.com/openshift/prometheus/pull/145
One advantage is that everything's self-contained (no need to update 2 repositories).

**Comment by raptorsun** [comment]
/close

This PR is closed because it is unnecessary now.

**Pull request closed without merging**
